name: nocoffee
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-288.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  intl: ^0.18.0
  flutter_riverpod: ^2.3.2
  shared_preferences: ^2.0.20
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_dotenv: ^5.0.2
  webview_flutter: ^4.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^5.0.3


flutter:
  uses-material-design: true

