name: nocoffee
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  intl: ^0.18.0
  flutter_riverpod: ^2.3.2
  shared_preferences: ^2.0.20
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_dotenv: ^5.0.2
  webview_flutter: ^4.0.2
  hive: ^2.2.3
  hive_flutter:
  table_calendar: ^3.0.9
  currency_text_input_formatter: ^2.1.9
  fl_chart: ^0.61.0
  syncfusion_flutter_charts: ^21.1.39
  fluttertoast: ^8.2.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  hive_generator:
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  auto_route_generator: ^5.0.3


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app_icon/
  fonts:
    # 스포카 한 산스
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.otf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.otf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.otf
          weight: 600

flutter_icons:
  android: "launcher_icon" # android manifest랑 동일해야함
  ios: false
  image_path_android: "assets/app_icon/app_icon.png"
  adaptive_icon_background: "assets/app_icon/icon_background.png"
  adaptive_icon_foreground: "assets/app_icon/icon_foreground.png"